#! /bin/sh
xrandr --output eDP1 --primary --mode 1920x1080 --output HDMI1 --above eDP1
feh --bg-scale ~/pix/wave.png
pgrep bspswallow || bspswallow &

killall polybar
bash ~/.config/polybar/launch.sh --cuts &


pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
#alacritty &
dunst &
killall unclutter
unclutter --ignore-scrolling &


libinput-gestures-setup start




bspc monitor eDP1 -d I II III IV V
bspc config border_width        2
bspc config window_gap			16

bspc config pointer_mod         mod4
bspc config pointer_action1     move
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 5
bspc config bottom_padding 25
# Colors
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"

bspc config split_ratio          0.60
bspc config focus_follows_pointer true


bspc rule -a "Brave" desktop=^2
bspc rule -a "*" state=tiled
bspc rule -a "Desktop — Plasma" state=floating
bspc rule -a "krunner" state=floating
bspc rule -a "plasmashell" state=floating
bspc rule -a "Plasma" state=floating
bspc rule -a "plasma-desktop" state=floating
bspc rule -a "Kmix" state=floating
